logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  servlet:
    context-path: /searcher-api

