i18n:
  basename: i18n/messages
  locale:
    default-value: en
    supported: en,es
logging:
  level:
    org:
      hibernate:
        stat: error
        type: error
management:
  endpoint:
    health:
      show-components: always
      show-details: always
spring:
  profiles:
    active: "prod"
jwt:
  secret: QeThWmZq4t7w!z%C*F)J@NcRfUjXn2r5u8x/A?D(G+KaPdSgVkYp3s6v9y$B&E)H
  authUrl: /v1/auth/authenticate
  expirationTimeInMilliseconds: 864000000

